### ISSUE TITLE
Date on gaf list, momentjs

### ISSUE THREAD

**Issue by elenimijalis** [elenimijalis/cacao-lite#27]

**Comment by hexylena** [comment]
I might be behind on the docker branch which I'm building from, but I'm currently seeing this:
![utvalg_999 063](https://cloud.githubusercontent.com/assets/458683/18010547/7dc0d048-6ba0-11e6-9745-cd1a23fe42a1.png)

![utvalg_999 064](https://cloud.githubusercontent.com/assets/458683/18010631/d0a4096a-6ba0-11e6-9498-48bb28962f07.png)

**Comment by elenimijalis** [comment]
Mine shows the correctly-formatted dates on gaf/list, but thanks for pointing out the team annotations. I must have missed that one.
